version: '2'
services:

  xds-server:
    build:
      context: .
      dockerfile: Dockerfile.xds
    ports:
      - "18000:18000"
    networks:
      - envoy-network

  on-prem-envoy:
    image: debug/envoy:latest
    volumes:
      - ./onprem-envoy.yaml:/etc/on-prem-envoy.yaml
    command: envoy -c /etc/on-prem-envoy.yaml --concurrency 1 -l trace --drain-time-s 3
    ports:
      # Admin interface
      - "8888:8888"
      # Reverse connection API listener
      - "9000:9000"
      # Ingress HTTP listener
      - "6060:6060"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - envoy-network
    depends_on:
      - xds-server
      - on-prem-service

  on-prem-service:
    image: nginxdemos/hello:plain-text
    networks:
      - envoy-network

  cloud-envoy:
    image: debug/envoy:latest
    volumes:
      - ./cloud-envoy.yaml:/etc/cloud-envoy.yaml
    command: envoy -c /etc/cloud-envoy.yaml --concurrency 1 -l trace --drain-time-s 3
    ports:
      # Admin interface
      - "8889:8888"
      # Reverse connection API listener
      - "9001:9000"
      # Egress listener
      - "8085:8085"
    networks:
      - envoy-network

networks:
  envoy-network:
    driver: bridge